#############################################################################
# Makefile for building: graphquant
# Generated by qmake (2.01a) (Qt 4.8.6) on: Thu Jun 26 07:03:53 2014
# Project:  graphquant.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -o Makefile graphquant.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQXT_GUI_LIB -DQXT_CORE_LIB -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I/usr/include/qt4/QxtCore -I/usr/include/qt4/QxtGui -I. -I/usr/include -I/usr/include/QxtGui -I/usr/include/QxtCore -I.
LINK          = g++
LFLAGS        = -Wl,-O1,--sort-common,--as-needed,-z,relro -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lopencv_core -lopencv_imgproc -lopencv_highgui -lmuparser -L/usr/lib -lQxtGui -lQxtCore -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cc \
		graph.cc \
		axis.cc moc_main.cpp \
		moc_graph.cpp \
		moc_axis.cpp \
		qrc_resources.cpp
OBJECTS       = main.o \
		graph.o \
		axis.o \
		moc_main.o \
		moc_graph.o \
		moc_axis.o \
		qrc_resources.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qxtvars.prf \
		/usr/share/qt4/mkspecs/features/qxt.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		graphquant.pro
QMAKE_TARGET  = graphquant
DESTDIR       = 
TARGET        = graphquant

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: graphquant.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qxtvars.prf \
		/usr/share/qt4/mkspecs/features/qxt.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -o Makefile graphquant.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/qxtvars.prf:
/usr/share/qt4/mkspecs/features/qxt.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile graphquant.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/graphquant1.0.0 || $(MKDIR) .tmp/graphquant1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/graphquant1.0.0/ && $(COPY_FILE) --parents main.h graph.h axis.h .tmp/graphquant1.0.0/ && $(COPY_FILE) --parents resources.qrc .tmp/graphquant1.0.0/ && $(COPY_FILE) --parents main.cc graph.cc axis.cc .tmp/graphquant1.0.0/ && (cd `dirname .tmp/graphquant1.0.0` && $(TAR) graphquant1.0.0.tar graphquant1.0.0 && $(COMPRESS) graphquant1.0.0.tar) && $(MOVE) `dirname .tmp/graphquant1.0.0`/graphquant1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/graphquant1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_main.cpp moc_graph.cpp moc_axis.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_main.cpp moc_graph.cpp moc_axis.cpp
moc_main.cpp: graph.h \
		axis.h \
		/usr/include/QxtGui/qxtlabel.h \
		/usr/include/QxtCore/qxtnamespace.h \
		/usr/include/QxtCore/qxtglobal.h \
		/usr/include/opencv2/imgproc/imgproc.hpp \
		/usr/include/opencv2/core/core.hpp \
		/usr/include/opencv2/core/types_c.h \
		/usr/include/assert.h \
		/usr/include/features.h \
		/usr/include/stdc-predef.h \
		/usr/include/sys/cdefs.h \
		/usr/include/bits/wordsize.h \
		/usr/include/gnu/stubs.h \
		/usr/include/gnu/stubs-32.h \
		/usr/include/gnu/stubs-64.h \
		/usr/include/stdlib.h \
		/usr/include/bits/waitflags.h \
		/usr/include/bits/waitstatus.h \
		/usr/include/endian.h \
		/usr/include/bits/endian.h \
		/usr/include/bits/byteswap.h \
		/usr/include/bits/types.h \
		/usr/include/bits/typesizes.h \
		/usr/include/bits/byteswap-16.h \
		/usr/include/xlocale.h \
		/usr/include/sys/types.h \
		/usr/include/time.h \
		/usr/include/bits/time.h \
		/usr/include/bits/timex.h \
		/usr/include/sys/select.h \
		/usr/include/bits/select.h \
		/usr/include/bits/sigset.h \
		/usr/include/bits/select2.h \
		/usr/include/sys/sysmacros.h \
		/usr/include/bits/pthreadtypes.h \
		/usr/include/alloca.h \
		/usr/include/bits/stdlib-bsearch.h \
		/usr/include/bits/stdlib-float.h \
		/usr/include/bits/stdlib.h \
		/usr/include/bits/stdlib-ldbl.h \
		/usr/include/string.h \
		/usr/include/bits/string.h \
		/usr/include/bits/string2.h \
		/usr/include/bits/string3.h \
		/usr/include/stdint.h \
		/usr/include/bits/wchar.h \
		/usr/include/math.h \
		/usr/include/bits/huge_val.h \
		/usr/include/bits/huge_valf.h \
		/usr/include/bits/huge_vall.h \
		/usr/include/bits/inf.h \
		/usr/include/bits/nan.h \
		/usr/include/bits/mathdef.h \
		/usr/include/bits/mathcalls.h \
		/usr/include/bits/mathinline.h \
		/usr/include/bits/math-finite.h \
		/usr/include/opencv2/core/version.hpp \
		/usr/include/limits.h \
		/usr/include/bits/posix1_lim.h \
		/usr/include/bits/local_lim.h \
		/usr/include/linux/limits.h \
		/usr/include/bits/posix2_lim.h \
		/usr/include/bits/xopen_lim.h \
		/usr/include/bits/stdio_lim.h \
		/usr/include/opencv2/core/operations.hpp \
		/usr/include/opencv2/core/mat.hpp \
		/usr/include/opencv2/imgproc/types_c.h \
		/usr/include/opencv2/core/core_c.h \
		/usr/include/opencv2/highgui/highgui.hpp \
		/usr/include/opencv2/highgui/highgui_c.h \
		/usr/include/muParser.h \
		/usr/include/muParserBase.h \
		/usr/include/muParserDef.h \
		/usr/include/muParserFixes.h \
		/usr/include/muParserStack.h \
		/usr/include/muParserError.h \
		/usr/include/muParserToken.h \
		/usr/include/muParserCallback.h \
		/usr/include/muParserTokenReader.h \
		/usr/include/muParserBytecode.h \
		/usr/include/muParserTemplateMagic.h \
		main.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) main.h -o moc_main.cpp

moc_graph.cpp: axis.h \
		/usr/include/QxtGui/qxtlabel.h \
		/usr/include/QxtCore/qxtnamespace.h \
		/usr/include/QxtCore/qxtglobal.h \
		/usr/include/opencv2/imgproc/imgproc.hpp \
		/usr/include/opencv2/core/core.hpp \
		/usr/include/opencv2/core/types_c.h \
		/usr/include/assert.h \
		/usr/include/features.h \
		/usr/include/stdc-predef.h \
		/usr/include/sys/cdefs.h \
		/usr/include/bits/wordsize.h \
		/usr/include/gnu/stubs.h \
		/usr/include/gnu/stubs-32.h \
		/usr/include/gnu/stubs-64.h \
		/usr/include/stdlib.h \
		/usr/include/bits/waitflags.h \
		/usr/include/bits/waitstatus.h \
		/usr/include/endian.h \
		/usr/include/bits/endian.h \
		/usr/include/bits/byteswap.h \
		/usr/include/bits/types.h \
		/usr/include/bits/typesizes.h \
		/usr/include/bits/byteswap-16.h \
		/usr/include/xlocale.h \
		/usr/include/sys/types.h \
		/usr/include/time.h \
		/usr/include/bits/time.h \
		/usr/include/bits/timex.h \
		/usr/include/sys/select.h \
		/usr/include/bits/select.h \
		/usr/include/bits/sigset.h \
		/usr/include/bits/select2.h \
		/usr/include/sys/sysmacros.h \
		/usr/include/bits/pthreadtypes.h \
		/usr/include/alloca.h \
		/usr/include/bits/stdlib-bsearch.h \
		/usr/include/bits/stdlib-float.h \
		/usr/include/bits/stdlib.h \
		/usr/include/bits/stdlib-ldbl.h \
		/usr/include/string.h \
		/usr/include/bits/string.h \
		/usr/include/bits/string2.h \
		/usr/include/bits/string3.h \
		/usr/include/stdint.h \
		/usr/include/bits/wchar.h \
		/usr/include/math.h \
		/usr/include/bits/huge_val.h \
		/usr/include/bits/huge_valf.h \
		/usr/include/bits/huge_vall.h \
		/usr/include/bits/inf.h \
		/usr/include/bits/nan.h \
		/usr/include/bits/mathdef.h \
		/usr/include/bits/mathcalls.h \
		/usr/include/bits/mathinline.h \
		/usr/include/bits/math-finite.h \
		/usr/include/opencv2/core/version.hpp \
		/usr/include/limits.h \
		/usr/include/bits/posix1_lim.h \
		/usr/include/bits/local_lim.h \
		/usr/include/linux/limits.h \
		/usr/include/bits/posix2_lim.h \
		/usr/include/bits/xopen_lim.h \
		/usr/include/bits/stdio_lim.h \
		/usr/include/opencv2/core/operations.hpp \
		/usr/include/opencv2/core/mat.hpp \
		/usr/include/opencv2/imgproc/types_c.h \
		/usr/include/opencv2/core/core_c.h \
		/usr/include/opencv2/highgui/highgui.hpp \
		/usr/include/opencv2/highgui/highgui_c.h \
		/usr/include/muParser.h \
		/usr/include/muParserBase.h \
		/usr/include/muParserDef.h \
		/usr/include/muParserFixes.h \
		/usr/include/muParserStack.h \
		/usr/include/muParserError.h \
		/usr/include/muParserToken.h \
		/usr/include/muParserCallback.h \
		/usr/include/muParserTokenReader.h \
		/usr/include/muParserBytecode.h \
		/usr/include/muParserTemplateMagic.h \
		graph.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) graph.h -o moc_graph.cpp

moc_axis.cpp: /usr/include/QxtGui/qxtlabel.h \
		/usr/include/QxtCore/qxtnamespace.h \
		/usr/include/QxtCore/qxtglobal.h \
		axis.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) axis.h -o moc_axis.cpp

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		images/icon.png \
		images/save.png
	/usr/lib/qt4/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

main.o: main.cc main.h \
		graph.h \
		axis.h \
		/usr/include/QxtGui/qxtlabel.h \
		/usr/include/QxtCore/qxtnamespace.h \
		/usr/include/QxtCore/qxtglobal.h \
		/usr/include/opencv2/imgproc/imgproc.hpp \
		/usr/include/opencv2/core/core.hpp \
		/usr/include/opencv2/core/types_c.h \
		/usr/include/assert.h \
		/usr/include/features.h \
		/usr/include/stdc-predef.h \
		/usr/include/sys/cdefs.h \
		/usr/include/bits/wordsize.h \
		/usr/include/gnu/stubs.h \
		/usr/include/gnu/stubs-32.h \
		/usr/include/gnu/stubs-64.h \
		/usr/include/stdlib.h \
		/usr/include/bits/waitflags.h \
		/usr/include/bits/waitstatus.h \
		/usr/include/endian.h \
		/usr/include/bits/endian.h \
		/usr/include/bits/byteswap.h \
		/usr/include/bits/types.h \
		/usr/include/bits/typesizes.h \
		/usr/include/bits/byteswap-16.h \
		/usr/include/xlocale.h \
		/usr/include/sys/types.h \
		/usr/include/time.h \
		/usr/include/bits/time.h \
		/usr/include/bits/timex.h \
		/usr/include/sys/select.h \
		/usr/include/bits/select.h \
		/usr/include/bits/sigset.h \
		/usr/include/bits/select2.h \
		/usr/include/sys/sysmacros.h \
		/usr/include/bits/pthreadtypes.h \
		/usr/include/alloca.h \
		/usr/include/bits/stdlib-bsearch.h \
		/usr/include/bits/stdlib-float.h \
		/usr/include/bits/stdlib.h \
		/usr/include/bits/stdlib-ldbl.h \
		/usr/include/string.h \
		/usr/include/bits/string.h \
		/usr/include/bits/string2.h \
		/usr/include/bits/string3.h \
		/usr/include/stdint.h \
		/usr/include/bits/wchar.h \
		/usr/include/math.h \
		/usr/include/bits/huge_val.h \
		/usr/include/bits/huge_valf.h \
		/usr/include/bits/huge_vall.h \
		/usr/include/bits/inf.h \
		/usr/include/bits/nan.h \
		/usr/include/bits/mathdef.h \
		/usr/include/bits/mathcalls.h \
		/usr/include/bits/mathinline.h \
		/usr/include/bits/math-finite.h \
		/usr/include/opencv2/core/version.hpp \
		/usr/include/limits.h \
		/usr/include/bits/posix1_lim.h \
		/usr/include/bits/local_lim.h \
		/usr/include/linux/limits.h \
		/usr/include/bits/posix2_lim.h \
		/usr/include/bits/xopen_lim.h \
		/usr/include/bits/stdio_lim.h \
		/usr/include/opencv2/core/operations.hpp \
		/usr/include/opencv2/core/mat.hpp \
		/usr/include/opencv2/imgproc/types_c.h \
		/usr/include/opencv2/core/core_c.h \
		/usr/include/opencv2/highgui/highgui.hpp \
		/usr/include/opencv2/highgui/highgui_c.h \
		/usr/include/muParser.h \
		/usr/include/muParserBase.h \
		/usr/include/muParserDef.h \
		/usr/include/muParserFixes.h \
		/usr/include/muParserStack.h \
		/usr/include/muParserError.h \
		/usr/include/muParserToken.h \
		/usr/include/muParserCallback.h \
		/usr/include/muParserTokenReader.h \
		/usr/include/muParserBytecode.h \
		/usr/include/muParserTemplateMagic.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cc

graph.o: graph.cc graph.h \
		axis.h \
		/usr/include/QxtGui/qxtlabel.h \
		/usr/include/QxtCore/qxtnamespace.h \
		/usr/include/QxtCore/qxtglobal.h \
		/usr/include/opencv2/imgproc/imgproc.hpp \
		/usr/include/opencv2/core/core.hpp \
		/usr/include/opencv2/core/types_c.h \
		/usr/include/assert.h \
		/usr/include/features.h \
		/usr/include/stdc-predef.h \
		/usr/include/sys/cdefs.h \
		/usr/include/bits/wordsize.h \
		/usr/include/gnu/stubs.h \
		/usr/include/gnu/stubs-32.h \
		/usr/include/gnu/stubs-64.h \
		/usr/include/stdlib.h \
		/usr/include/bits/waitflags.h \
		/usr/include/bits/waitstatus.h \
		/usr/include/endian.h \
		/usr/include/bits/endian.h \
		/usr/include/bits/byteswap.h \
		/usr/include/bits/types.h \
		/usr/include/bits/typesizes.h \
		/usr/include/bits/byteswap-16.h \
		/usr/include/xlocale.h \
		/usr/include/sys/types.h \
		/usr/include/time.h \
		/usr/include/bits/time.h \
		/usr/include/bits/timex.h \
		/usr/include/sys/select.h \
		/usr/include/bits/select.h \
		/usr/include/bits/sigset.h \
		/usr/include/bits/select2.h \
		/usr/include/sys/sysmacros.h \
		/usr/include/bits/pthreadtypes.h \
		/usr/include/alloca.h \
		/usr/include/bits/stdlib-bsearch.h \
		/usr/include/bits/stdlib-float.h \
		/usr/include/bits/stdlib.h \
		/usr/include/bits/stdlib-ldbl.h \
		/usr/include/string.h \
		/usr/include/bits/string.h \
		/usr/include/bits/string2.h \
		/usr/include/bits/string3.h \
		/usr/include/stdint.h \
		/usr/include/bits/wchar.h \
		/usr/include/math.h \
		/usr/include/bits/huge_val.h \
		/usr/include/bits/huge_valf.h \
		/usr/include/bits/huge_vall.h \
		/usr/include/bits/inf.h \
		/usr/include/bits/nan.h \
		/usr/include/bits/mathdef.h \
		/usr/include/bits/mathcalls.h \
		/usr/include/bits/mathinline.h \
		/usr/include/bits/math-finite.h \
		/usr/include/opencv2/core/version.hpp \
		/usr/include/limits.h \
		/usr/include/bits/posix1_lim.h \
		/usr/include/bits/local_lim.h \
		/usr/include/linux/limits.h \
		/usr/include/bits/posix2_lim.h \
		/usr/include/bits/xopen_lim.h \
		/usr/include/bits/stdio_lim.h \
		/usr/include/opencv2/core/operations.hpp \
		/usr/include/opencv2/core/mat.hpp \
		/usr/include/opencv2/imgproc/types_c.h \
		/usr/include/opencv2/core/core_c.h \
		/usr/include/opencv2/highgui/highgui.hpp \
		/usr/include/opencv2/highgui/highgui_c.h \
		/usr/include/muParser.h \
		/usr/include/muParserBase.h \
		/usr/include/muParserDef.h \
		/usr/include/muParserFixes.h \
		/usr/include/muParserStack.h \
		/usr/include/muParserError.h \
		/usr/include/muParserToken.h \
		/usr/include/muParserCallback.h \
		/usr/include/muParserTokenReader.h \
		/usr/include/muParserBytecode.h \
		/usr/include/muParserTemplateMagic.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graph.o graph.cc

axis.o: axis.cc axis.h \
		/usr/include/QxtGui/qxtlabel.h \
		/usr/include/QxtCore/qxtnamespace.h \
		/usr/include/QxtCore/qxtglobal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o axis.o axis.cc

moc_main.o: moc_main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_main.o moc_main.cpp

moc_graph.o: moc_graph.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_graph.o moc_graph.cpp

moc_axis.o: moc_axis.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_axis.o moc_axis.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

